In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
def predict_func(slope,intercept,x_test):
    #
    #pred = []
    #n_data = x_test.shape[0]
    #x_test.values.tolist()
    #for i in range(n_data):
    #    pred.append(((slope * x_test[i]) + intercept).tolist)
    #temp = np.dot(slope, x_test.T)
    pred = ((np.dot(x_test, slope)) + intercept)
        
    return pred

In [3]:
def mse_calc(prediction, y_test):
    #
    #total_data = len(prediction)
    #error = 0
    error = np.mean((prediction - y_test)**2)
    return error

In [4]:
#gradient descent 
def grad_descent(s_theta, l_rate, tolerance, iter_val, x_train, y_train):
    
    n_data = len(x_train)
    bias = np.ones((n_data,1))
    s_intercept = s_theta[0]
    s_slope = s_theta[1:]
    prediction = predict_func(s_slope, s_intercept, x_train)
    error =  mse_calc(prediction, y_train)
    x_train_b = np.append(bias, x_train, axis = 1) 
    
    for i in range(iter_val):
        int_theta = [0 for i in range(len(x_train[0]) + 1)]
        #int_intercept = 0
        n_pt = float(len(x_train))
        
        prediction = predict_func(s_slope, s_intercept, x_train)
        #prev_error = error
        #for i in range(len(x_train)):
        
        #int_intercept = 2 / n_pt * np.dot(bias.T, (prediction - y_train))
        #int_slope = 2 / n_pt * np.dot(x_train.T, (prediction - y_train))
        
        int_theta = 2 / n_pt * np.dot(x_train_b.T, (prediction - y_train))
            
        #final_slope = s_slope - (l_rate * int_slope)
        #final_intercept = s_intercept - (l_rate * int_intercept)
        #s_slope = final_slope
        #s_intercept = final_intercept
        
        s_theta -=  l_rate * int_theta
        
        #prediction = predict_func(s_slope, s_intercept, x_train)
        #error = mse_calc(prediction, y_train)
        
        #if ((prev_error - error) / prev_error) <= tolerance:
        #    break
        
    s_intercept = s_theta[0]
    s_slope = s_theta[1:]
    prediction = predict_func(s_slope, s_intercept, x_train)
    final_error = mse_calc(prediction, y_train)
        
    return  s_theta, final_error

In [5]:
X = 2 * np.random.rand(100,1)
y = 4 +3 * X+np.random.randn(100,1)
#X

In [6]:
theta = np.zeros((len(X[0]) + 1, 1))
tolerance = 0.0001
l_rate = 0.01
iterations = 5000

In [7]:
theta

array([[0.],
       [0.]])

In [8]:
grad_theta, grad_error = grad_descent(theta, l_rate, tolerance, iterations, X, y)
grad_theta, grad_error

(array([[3.75360608],
        [3.0866774 ]]),
 1.0222778792747405)

In [9]:
n_data = len(X)
bias = np.ones((n_data,1))

x_train_b = np.append(bias, X, axis = 1)
#x_train_b

In [10]:
prediction = predict_func(theta[1:], theta[0], X)
#prediction
(prediction - y).T


array([[-1.09292489,  1.03302287, -1.21559585, -1.10428989, -1.94536545,
         0.43931395, -0.84421083, -1.22386004,  0.99673265,  0.0370241 ,
        -0.37002091,  1.00253113,  0.11863346, -0.99686692, -0.82766364,
        -2.03556843, -0.50302048,  0.82847028,  0.25926853,  0.64861077,
         0.55652652, -0.68862287, -0.76967787,  1.67844211,  0.64850037,
         0.4817741 ,  2.72082258,  1.18330139, -0.61162892,  0.6161869 ,
         0.74882503,  1.13241374,  1.55191384,  0.20066316,  0.2416971 ,
        -0.18330927, -0.94271385, -0.07316254, -0.24755037, -1.65456358,
        -0.59691818, -1.03300824,  0.84619492,  0.0698201 , -0.60866548,
         0.89128418, -0.16851683, -0.49337122,  2.45242193, -0.31126064,
         0.51564258, -1.04712846, -0.94772185, -0.79326334,  0.06773543,
        -0.08491425, -0.73584883,  1.55880759, -1.27490644,  0.40006766,
         0.15820508,  0.69497377,  0.25501223, -1.53526753,  0.70158944,
         0.95995439, -1.06500002, -1.89485432, -0.1

In [11]:
int_theta = 1 / (2*n_data) * np.dot(x_train_b.T, (prediction - y))
int_theta * l_rate
theta - int_theta * l_rate

array([[3.75360608],
       [3.0866774 ]])